---
- name: Backup running-config from IOS-XE devices
  hosts: iosxe
  gather_facts: False
  vars_files:
    - vault.yml

  tasks:
    - name: Collect running configuration
      cisco.ios.ios_command:
        commands: show running-config
      register: run_cfg

    - name: Ensure backup directory exists
      local_action:
        module: file
        path: "{{ backup_dir }}"
        state: directory
      run_once: True

    - name: Save config to local file
      local_action:
        module: copy
        content: "{{ run_cfg.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}.cfg"
      run_once: False

- name: Backup running-config from NX-OS devices
  hosts: nxos
  gather_facts: False
  vars_files:
    - vault.yml

  tasks:
    - name: Collect running configuration
      cisco.nxos.nxos_command:
        commands: show running-config
      register: run_cfg

    - name: Ensure backup directory exists
      local_action:
        module: file
        path: "{{ backup_dir }}"
        state: directory
      run_once: True

    - name: Save config to local file
      local_action:
        module: copy
        content: "{{ run_cfg.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}.cfg"
      run_once: False